"""
Default parameter key constants and global configuration metadata for SubScript.

This module defines two classes used throughout the SubScript library:

- :class:`ParamKeys`: A namespace of string constants mapping friendly Python
  attribute names to the corresponding Galacticus HDF5 dataset keys.  Import
  this class and reference its attributes instead of hard-coding raw strings
  to make analysis code robust against future Galacticus naming changes.

- :class:`Meta`: Global configuration flags that control runtime behaviour
  such as astropy unit handling and output formatting.  These class attributes
  are read (and written) by other SubScript modules; treat them as a simple
  global settings object.
"""

from astropy import units as apu    

class ParamKeys():
    """
    Namespace of default Galacticus HDF5 dataset key strings.

    Each attribute maps a descriptive Python name to the exact string key
    used in Galacticus nodeData HDF5 groups.  Use these constants throughout
    analysis code rather than raw string literals to avoid typos and to make
    code resilient to upstream naming changes.

    Notes
    -----
    Keys prefixed ``custom_`` are *not* native Galacticus outputs; they are
    generated by SubScript helper functions (e.g. :func:`~subscript.tabulatehdf5.get_custom_dsets`)
    and injected into :class:`~subscript.tabulatehdf5.NodeProperties` objects at
    load time.
    """

    # --- Orbital position coordinates (Galacticus internal frame, SI: metres) ---

    x = 'positionOrbitalX'
    """x orbital position coordinate of the node."""

    y = 'positionOrbitalY'
    """y orbital position coordinate of the node."""

    z = 'positionOrbitalZ'
    """z orbital position coordinate of the node."""

    # --- Satellite-relative position coordinates (SI: metres) ---

    relx = 'satellitePositionX'
    """x position of the satellite relative to its host halo."""

    rely = 'satellitePositionY'
    """y position of the satellite relative to its host halo."""

    relz = 'satellitePositionZ'
    """z position of the satellite relative to its host halo."""

    # --- Masses (SI: kg) ---

    mass = 'basicMass'
    """Basic (total) mass of the node.  Alias for :attr:`mass_basic`."""

    mass_bound = 'satelliteBoundMass'
    """Gravitationally bound mass remaining in the satellite subhalo (SI: kg)."""

    mass_basic = 'basicMass'
    """Basic (total) mass of the node (SI: kg).  Same as :attr:`mass`."""

    # --- Halo structural radii (SI: metres) ---

    rvir = 'darkMatterOnlyRadiusVirial'
    """Virial radius of the dark-matter-only halo (SI: m)."""

    rscale = 'darkMatterProfileScaleRadius'
    """NFW scale radius of the dark matter profile (SI: m).  Alias for :attr:`scale_radius`."""

    scale_radius = 'darkMatterProfileScaleRadius'
    """NFW scale radius of the dark matter profile (SI: m).  Same as :attr:`rscale`."""

    # --- Node topology / isolation ---

    is_isolated = 'nodeIsIsolated'
    """
    Integer flag indicating whether the node is an isolated (host) halo.
    1 = isolated host halo; 0 = subhalo / satellite.
    """

    hierarchylevel = 'nodeHierarchyLevel'
    """Hierarchy level of the node within the merger tree (0 = root/host halo)."""

    # --- Spheroid / disk structural properties ---

    sphere_radius = 'spheroidRadius'
    """Half-mass radius of the spheroidal component (SI: m)."""

    sphere_anglularmomentum = 'spheroidAngularMomentum'
    """Angular momentum of the spheroidal component (SI: kg m^2 s^-1)."""

    sphere_mass_stellar = 'spheroidMassStellar'
    """Stellar mass of the spheroidal component (SI: kg)."""

    sphere_mass_gas = 'spheroidMassGas'
    """Gas mass of the spheroidal component (SI: kg)."""

    # --- Density profile ---

    density_profile_radius = 'densityProfileRadius'
    """Radii at which the density profile is sampled (SI: m)."""

    density_profile = 'densityProfile'
    """Dark matter density profile values at each sampled radius (SI: kg m^-3)."""

    # --- Redshift / time ---

    z_lastisolated = 'redshiftLastIsolated'
    """Redshift at which the node was last an isolated (host) halo."""

    basic_time_last_isolated = 'basicTimeLastIsolated'
    """Cosmic time at which the node was last isolated (SI: s)."""

    # --- Truncated NFW (tNFW) profile parameters ---

    tnfw_rt = 'radiusTidalTruncationNFW'
    """Tidal truncation radius of the NFW profile (SI: m)."""

    tnfw_p0 = 'densityNormalizationTidalTruncationNFW'
    """Density normalisation of the tidally truncated NFW profile (SI: kg m^-3)."""

    # --- Custom / synthetic dataset keys (added by SubScript, not native Galacticus) ---

    custom_id = 'custom_id'
    """Auto-assigned unique integer identifier for each node within an output."""

    custom_tree_index = 'custom_node_tree'
    """Index of the merger tree that each node belongs to."""

    custom_tree_outputorder = 'custom_node_outputorder'
    """Sequential output-order index of the tree that each node belongs to."""

    # --- Concentration ---

    concentration = 'concentration'
    """Halo concentration parameter (dimensionless)."""

    # --- Merger-tree bookkeeping ---

    merger_tree_count = 'mergerTreeCount'
    """Number of nodes in each merger tree (one entry per tree)."""

    merger_tree_index = 'mergerTreeIndex'
    """Unique integer index identifying each merger tree."""

    merger_tree_seed = 'mergerTreeSeed'
    """Random seed used to generate the merger tree."""

    merger_tree_start_index = 'mergerTreeStartIndex'
    """Index of the first node in the merger tree within the flat nodeData arrays."""

    merger_tree_weight = 'mergerTreeWeight'
    """Statistical weight assigned to the merger tree for ensemble averaging."""

    # --- Dark-matter-only halo thermodynamic / kinematic properties ---

    dark_matter_temperature_virial = 'darkMatterOnlyTemperatureVirial'
    """Virial temperature of the dark-matter-only halo (SI: K)."""

    dark_matter_velocity_virial = 'darkMatterOnlyVelocityVirial'
    """Virial velocity (circular speed at the virial radius) of the DMO halo (SI: m s^-1)."""

    dark_matter_profile_dmo_radius_velocity_max = 'darkMatterProfileDMORadiusVelocityMaximum'
    """Radius at which the DMO circular velocity curve peaks (SI: m)."""

    dark_matter_profile_dmo_velocity_max = 'darkMatterProfileDMOVelocityMaximum'
    """Peak circular velocity of the DMO halo (SI: m s^-1)."""

    dark_matter_profile_scale = 'darkMatterProfileScale'
    """Scale parameter of the dark matter profile (SI: m)."""

    # --- Enclosed mass ---

    mass_halo_enclosed_current = 'massHaloEnclosedCurrent'
    """Total mass enclosed within the current halo boundary (SI: kg)."""

    # --- Node hierarchy depth ---

    hierarchy_level_depth = 'nodeHierarchyLevelDepth'
    """Depth of the node's position within the sub-sub-halo hierarchy."""

    hierarchy_level_maximum = 'nodeHierarchyLevelMaximum'
    """Maximum hierarchy depth reached by this branch of the merger tree."""

    # --- Node indices ---

    node_index = 'nodeIndex'
    """Unique index identifying each node within a Galacticus output."""

    subsampling_weight = 'nodeSubsamplingWeight'
    """Statistical subsampling weight assigned to the node."""

    parent_index = 'parentIndex'
    """Node index of the parent (host) node in the merger tree."""

    satellite_index = 'satelliteIndex'
    """Node index of the satellite within its host halo."""

    # --- Satellite kinematics (SI: m s^-1) ---

    satellite_velocity_x = 'satelliteVelocityX'
    """x component of the satellite velocity relative to its host halo."""

    satellite_velocity_y = 'satelliteVelocityY'
    """y component of the satellite velocity relative to its host halo."""

    satellite_velocity_z = 'satelliteVelocityZ'
    """z component of the satellite velocity relative to its host halo."""

    # --- Satellite tidal effects ---

    satellite_tidal_field = 'satelliteTidalField'
    """Tidal field strength experienced by the satellite (SI: s^-2)."""

    satellite_tidal_heating_normalized = 'satelliteTidalHeatingNormalized'
    """Normalized cumulative tidal heating of the satellite (SI: kg s^-2)."""

    # --- Tree topology ---

    sibling_index = 'siblingIndex'
    """Node index of the sibling node in the merger tree."""

    # --- Spin angular momentum (dimensionless Bullock spin parameter) ---

    spin_angular_momentum = 'spinAngularMomentum'
    """Spin parameter (dimensionless) of the halo."""

    spin_angular_momentum_vector_x = 'spinAngularMomentumVectorX'
    """x component of the dimensionless spin angular momentum vector."""

    spin_angular_momentum_vector_y = 'spinAngularMomentumVectorY'
    """y component of the dimensionless spin angular momentum vector."""

    spin_angular_momentum_vector_z = 'spinAngularMomentumVectorZ'
    """z component of the dimensionless spin angular momentum vector."""

    
class Meta():
    """
    Global runtime configuration for the SubScript library.

    All attributes are class-level (not instance-level).  Other modules read
    and write these attributes directly to share state without passing
    configuration through every function call.

    Attributes
    ----------
    disableDepreciatedWarning : bool
        If ``True``, suppress :class:`DeprecationWarning` messages issued by
        deprecated SubScript functions.  Default ``False``.
    units_enable : bool
        If ``True``, node properties are returned as :class:`astropy.units.Quantity`
        objects with physical units.  Default ``False``.
    units_in_si : dict or None
        Dictionary mapping :class:`ParamKeys` string keys to the corresponding
        :mod:`astropy.units` unit objects (in SI).  Populated by
        :func:`~subscript.units.enableUnits`.  Default ``None``.
    units_in_si_conversion : dict or None
        Dictionary mapping :class:`ParamKeys` string keys to numerical conversion
        factors that transform raw Galacticus values into SI units.  Populated by
        :func:`~subscript.units.enableUnits`.  Default ``None``.
    unit_bases : list of astropy.units.Unit
        Base units used when decomposing :class:`~astropy.units.Quantity` results.
        Default ``[Msun, Mpc, Myr]``.
    disable_auto_format_scalar : bool
        If a wrapped function returns a single-element array per tree
        (e.g. ``[[1.0], [1.0], [1.0]]``), SubScript normally collapses this to
        a 1-D array (e.g. ``[1.0, 1.0, 1.0]``).  Set to ``True`` to disable
        this automatic flattening.  Default ``False``.

        .. warning::
           This flag may be changed to default ``True`` in a future release.
           New code should set ``disable_auto_format_scalar = True`` and handle
           the output shape explicitly.
    """

    disableDepreciatedWarning = False
    """If true, disable the warning about deprecated code."""

    units_enable = False
    """If true, use astropy units when reading data."""

    units_in_si = None
    """Dictionary mapping parameter keys to their corresponding astropy units in SI."""   

    units_in_si_conversion = None
    """Dictionary mapping parameter keys to a numerical value that converts the nodeProperty to an SI unit."""

    unit_bases = [apu.Msun, apu.Mpc, apu.Myr]
    """List of astropy units to use as bases for unit conversions."""

    disable_auto_format_scalar = False
    """
    If a function only outputs a single single value in an array per tree, 
    Ie [[1.0], [1.0], [1.0]], then automatically convert to a 1d array, Ie [1.0, 1.0, 1.0].
    If true, disable this automatic formatting. 
    WARNING: This may be set to true in the future, but is currently not recommended to set to true as it may cause unexpected output formats.
    For new code use disable_auto_format_scalar = True and explicitly format the output as needed.
    """

